let angle_generator = new AngleGenerator()
console.log(angle_generator.angles)
let figure_generator = new FigureGenerator()
figure_generator.generateFigure(angle_generator.angles["start"], angle_generator.angles["end"])
all_buttons = document.querySelectorAll('.keyboard_button')
let angle_keyboard = new AngleKeyboard(all_buttons)
angle_keyboard.print_button_state()